// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdP2TcSLX8YB7qnfoD-KcVN3Q__29Gb8U',
    appId: '1:814749553313:web:54dd2710ff6995a8ced6e0',
    messagingSenderId: '814749553313',
    projectId: 'prjkt-boring',
    authDomain: 'prjkt-boring.firebaseapp.com',
    storageBucket: 'prjkt-boring.firebasestorage.app',
  databaseURL: 'https://prjkt-boring-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31gXLHfMUPcOjIkdLWAutNgHYGdQnJ0Q',
    appId: '1:814749553313:android:1fca9b3b8c6520b5ced6e0',
    messagingSenderId: '814749553313',
    projectId: 'prjkt-boring',
    storageBucket: 'prjkt-boring.firebasestorage.app',
  databaseURL: 'https://prjkt-boring-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4inSWSmE9lSz3x2iMewyEVEIdtprO3E',
    appId: '1:814749553313:ios:83c7d3d8366cb076ced6e0',
    messagingSenderId: '814749553313',
    projectId: 'prjkt-boring',
    storageBucket: 'prjkt-boring.firebasestorage.app',
    iosBundleId: 'com.example.messager',
  databaseURL: 'https://prjkt-boring-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4inSWSmE9lSz3x2iMewyEVEIdtprO3E',
    appId: '1:814749553313:ios:83c7d3d8366cb076ced6e0',
    messagingSenderId: '814749553313',
    projectId: 'prjkt-boring',
    storageBucket: 'prjkt-boring.firebasestorage.app',
    iosBundleId: 'com.example.messager',
  databaseURL: 'https://prjkt-boring-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdP2TcSLX8YB7qnfoD-KcVN3Q__29Gb8U',
    appId: '1:814749553313:web:369d8eec25833d58ced6e0',
    messagingSenderId: '814749553313',
    projectId: 'prjkt-boring',
    authDomain: 'prjkt-boring.firebaseapp.com',
    storageBucket: 'prjkt-boring.firebasestorage.app',
  databaseURL: 'https://prjkt-boring-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

}